name: Deployment to VPS
on:
  push:
    branches:
      - CD
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present        
        env:
          CI: false

      - name: Setup SSH Keys and known_hosts
        # env:
        #   SSH_HOST: ${{ secrets.HOST }}
        #   SSH_USERNAME: ${{ secrets.USERNAME }}
        #   SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        #   SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        - name: "Deploy to production"
          run: rsync -ravzp ./dist/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/new/