name: Deployment to VPS
on:
  push:
    branches:
      - CD
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present        
        env:
          CI: false
      - name: Copiando arquivos para VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /var/www/html/new
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: $${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo "🍏 O status do job é ${{ job.status }}."