name: Deployment to VPS
on:
  push:
    branches:
      - CD
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present        
        env:
          CI: false

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo -e "Host vps\n\tUser $SSH_USERNAME\n\tHostname $SSH_HOST\n\tStrictHostKeyChecking No" >> ~/.ssh/config
          echo "DEBUG: "
          cat ~/.ssh/id_rsa
          cat ~/.ssh/config
      - name: "Deploy to production"
        run: |
          rsync -ravzp dist $SSH_USERNAME@SSH_HOST:/var/www/html/new